import type { EndpointDef, FieldDef, ModuleKey } from "@/lib/telecomPremium/core";

export type PremiumConfig = {
  key: ModuleKey;
  title: string;
  badge: string;
  description: string;
  initialPayload: any;
  sections: Array<{ title: string; description: string; fields: FieldDef[] }>;
  endpoints: EndpointDef[];
  capabilities: string[];
};

const bool = ["true", "false"];

export const CONFIGS: Record<ModuleKey, PremiumConfig> = {
  rf: {
    key: "rf",
    title: "RF Premium Lab",
    badge: "RF · 3D antenna · Recharts",
    description: "Antena 3D, S11, VSWR, patrón polar, matching, sweep, IA y exportación realtime.",
    initialPayload: { antennaType:"helix", frecuenciaGHz:2.45, numRays:900000, geometry:{turns:7, helixRadiusMm:21.1, pitchAngleDeg:13, nSegments:181, conductorDiameterMm:2, groundPlaneRadiusMm:65}, matching:{targetOhm:50, network:"quarter_wave", stubEnabled:true, stripWidthMm:6, stripLengthMm:28}, sweep:{fStartGHz:2.0, fStopGHz:3.0, points:201} },
    sections: [
      { title:"Antena", description:"Parámetros de antena.", fields:[{path:"antennaType",label:"Tipo",type:"select",options:["dipole","helix","patch","array"]},{path:"frecuenciaGHz",label:"Frecuencia",type:"number",unit:"GHz"},{path:"numRays",label:"Rayos",type:"number"}] },
      { title:"Geometría", description:"Dimensiones 3D.", fields:[{path:"geometry.turns",label:"Vueltas",type:"number"},{path:"geometry.helixRadiusMm",label:"Radio",type:"number",unit:"mm"},{path:"geometry.pitchAngleDeg",label:"Pitch",type:"number",unit:"deg"},{path:"geometry.nSegments",label:"Segmentos",type:"number"},{path:"geometry.conductorDiameterMm",label:"Conductor",type:"number",unit:"mm"},{path:"geometry.groundPlaneRadiusMm",label:"Plano masa",type:"number",unit:"mm"}] },
      { title:"Matching/Sweep", description:"Adaptación y barrido.", fields:[{path:"matching.targetOhm",label:"Objetivo",type:"number",unit:"Ω"},{path:"matching.network",label:"Red",type:"select",options:["none","quarter_wave","stub","l_network"]},{path:"matching.stubEnabled",label:"Stub",type:"boolean",options:bool},{path:"sweep.fStartGHz",label:"Inicio",type:"number",unit:"GHz"},{path:"sweep.fStopGHz",label:"Fin",type:"number",unit:"GHz"},{path:"sweep.points",label:"Puntos",type:"number"}] },
    ],
    endpoints: [{label:"Estado RF",method:"GET",path:"/_rf_app/rf/health",payloadMode:"current"},{label:"RF IA",method:"POST",path:"/telecom/v500000000/manual-ai/generate",payloadMode:"custom",payload:{module:"rf",prompt:"antena premium 3D S11 VSWR matching",level:"pro"}},{label:"Industrial",method:"POST",path:"/telecom/v900000000/scenario/industrial",payloadMode:"global"}],
    capabilities: ["Three.js","S11","VSWR","polar","matching","IA","export"]
  },
  sionna: {
    key:"sionna",
    title:"Sionna Premium Lab",
    badge:"Sionna · 3D ray tracing · animated rays",
    description:"Editor 3D de edificio, TX/RX, materiales, columna térmica, rayos animados y live simulation.",
    initialPayload:{frecuenciaGHz:2.45,forceFallback:true,txPowerDbm:20,thermalTempK:700,maxDepth:6,samplesPerSrc:1000000,tx:[{id:"tx1",x:-2,y:1.2,z:0,powerDbm:20}],rx:[{id:"rx1",x:3,y:1.2,z:1},{id:"rx2",x:8,y:1.2,z:-1}],rooms:[{id:"r1",name:"Sala",x:0,z:0,width:8,length:6,height:2.8,material:"brick"},{id:"r2",name:"Despacho",x:7,z:0,width:5,length:5,height:2.8,material:"concrete"}],objects:[{id:"wall1",type:"box",x:3.5,y:1.4,z:0,sx:.25,sy:2.8,sz:6,material:"concrete"},{id:"thermal-column",type:"thermal_column",x:1,y:1.5,z:1,sx:.8,sy:3,sz:.8,material:"hot_air"}]},
    sections:[{title:"Solver",description:"Trazado y radio.",fields:[{path:"frecuenciaGHz",label:"Frecuencia",type:"number",unit:"GHz"},{path:"txPowerDbm",label:"TX",type:"number",unit:"dBm"},{path:"maxDepth",label:"Profundidad",type:"number"},{path:"samplesPerSrc",label:"Samples",type:"number"},{path:"forceFallback",label:"Fallback",type:"boolean",options:bool}]},{title:"Nodos",description:"Posiciones TX/RX.",fields:[{path:"tx.0.x",label:"TX X",type:"number"},{path:"tx.0.z",label:"TX Z",type:"number"},{path:"rx.0.x",label:"RX1 X",type:"number"},{path:"rx.0.z",label:"RX1 Z",type:"number"},{path:"rx.1.x",label:"RX2 X",type:"number"},{path:"rx.1.z",label:"RX2 Z",type:"number"}]},{title:"Edificio",description:"Materiales y columna.",fields:[{path:"rooms.0.material",label:"Material sala",type:"select",options:["brick","concrete","glass","wood","drywall"]},{path:"rooms.1.material",label:"Material despacho",type:"select",options:["brick","concrete","glass","wood","drywall"]},{path:"thermalTempK",label:"Temperatura",type:"number",unit:"K"},{path:"objects.1.x",label:"Columna X",type:"number"},{path:"objects.1.z",label:"Columna Z",type:"number"}]}],
    endpoints:[{label:"Estado Sionna",method:"GET",path:"/_sionna_app/sionna/health",payloadMode:"current"},{label:"Live 3D",method:"POST",path:"/telecom/v500000000/simulation/live",payloadMode:"custom",payload:{timeS:1,rfPowerDbm:20,people:4,opticalLengthKm:10,solarIrradianceWm2:850,frecuenciaGHz:2.45}},{label:"Sionna IA",method:"POST",path:"/telecom/v500000000/manual-ai/generate",payloadMode:"custom",payload:{module:"sionna",prompt:"edificio 3D ray tracing tx rx materiales columna termica",level:"pro"}}],
    capabilities:["Three.js","rayos animados","TX/RX","materiales","thermal","IA","export"]
  },
  optical: {
    key:"optical",title:"Optical Premium Lab",badge:"Optical · Eye diagram · WDM",description:"Fibra, WDM, eye diagram, BER/OSNR conceptual, presupuesto y FSO.",
    initialPayload:{wavelengthNm:1550,lengthKm:10,txPowerDbm:0,rxSensitivityDbm:-20,fiberType:"G652D",bitrateGbps:10,connectors:2,splices:4,marginDb:3,wdm:{channels:8,spacingGHz:100},fso:{enabled:false,distanceKm:1,visibilityKm:10}},
    sections:[{title:"Fibra",description:"Enlace.",fields:[{path:"wavelengthNm",label:"λ",type:"number",unit:"nm"},{path:"lengthKm",label:"Longitud",type:"number",unit:"km"},{path:"fiberType",label:"Fibra",type:"select",options:["G652D","G655","OM3","OM4"]},{path:"bitrateGbps",label:"Bitrate",type:"number",unit:"Gbps"}]},{title:"Balance",description:"Pérdidas.",fields:[{path:"txPowerDbm",label:"TX",type:"number",unit:"dBm"},{path:"rxSensitivityDbm",label:"RX",type:"number",unit:"dBm"},{path:"connectors",label:"Conectores",type:"number"},{path:"splices",label:"Empalmes",type:"number"},{path:"marginDb",label:"Margen",type:"number",unit:"dB"}]},{title:"WDM/FSO",description:"Canales.",fields:[{path:"wdm.channels",label:"Canales",type:"number"},{path:"wdm.spacingGHz",label:"Spacing",type:"number"},{path:"fso.enabled",label:"FSO",type:"boolean",options:bool},{path:"fso.distanceKm",label:"Distancia",type:"number"}]}],
    endpoints:[{label:"Estado óptica",method:"GET",path:"/_optical_app/optical/health",payloadMode:"current"},{label:"Óptica IA",method:"POST",path:"/telecom/v500000000/manual-ai/generate",payloadMode:"custom",payload:{module:"optical",prompt:"enlace optico WDM eye BER OSNR",level:"pro"}}],
    capabilities:["eye","WDM","BER","OSNR","FSO","IA","export"]
  },
  dsp: {
    key:"dsp",title:"DSP Premium Lab",badge:"DSP · FFT · STFT · spectrogram",description:"Waveform, FFT, espectrograma, VAD, modulación y BER.",
    initialPayload:{signal:{kind:"chirp",frequencyHz:1000,fs:16000,durationS:1,noiseStd:.01},stft:{nFft:512,hopLength:160,window:"hann"},vad:{threshold:.05,minVoiceMs:80,minSilenceMs:100},modulation:{scheme:"QPSK",snrDb:20,bits:10000}},
    sections:[{title:"Señal",description:"Fuente.",fields:[{path:"signal.kind",label:"Tipo",type:"select",options:["sine","chirp","noise"]},{path:"signal.frequencyHz",label:"Frecuencia",type:"number"},{path:"signal.fs",label:"fs",type:"number"},{path:"signal.durationS",label:"Duración",type:"number"}]},{title:"STFT/VAD",description:"Análisis.",fields:[{path:"stft.nFft",label:"NFFT",type:"number"},{path:"stft.hopLength",label:"Hop",type:"number"},{path:"stft.window",label:"Ventana",type:"select",options:["hann","hamming","blackman"]},{path:"vad.threshold",label:"Umbral",type:"number"}]},{title:"Modulación",description:"BER.",fields:[{path:"modulation.scheme",label:"Modulación",type:"select",options:["BPSK","QPSK","16QAM"]},{path:"modulation.snrDb",label:"SNR",type:"number"},{path:"modulation.bits",label:"Bits",type:"number"}]}],
    endpoints:[{label:"Estado DSP",method:"GET",path:"/_dsp_app/dsp/health",payloadMode:"current"},{label:"Pipeline DSP",method:"POST",path:"/_dsp_app/dsp/v40000/validation/pipeline",payloadMode:"current"},{label:"DSP IA",method:"POST",path:"/telecom/v500000000/manual-ai/generate",payloadMode:"custom",payload:{module:"dsp",prompt:"FFT STFT VAD BER espectrograma",level:"pro"}}],
    capabilities:["FFT","STFT","spectrogram","VAD","BER","IA","export"]
  },
  electronics: {
    key:"electronics",title:"Electronics Premium Lab",badge:"Electronics · PCB · thermal",description:"Esquemático, RC, divisor, fuente, PCB, térmica y potencia.",
    initialPayload:{divider:{vinV:5,r1Ohm:10000,r2Ohm:10000},rc:{rOhm:1000,cF:.000001,frequencyHz:1000},thermal:{powerW:2.5,thetaJaCPerW:40,ambientC:30},power:{vinV:12,voutV:5,ioutA:1,efficiency:.88},pcb:{layers:4,copperOz:1,boardAreaCm2:80}},
    sections:[{title:"Divisor",description:"Red resistiva.",fields:[{path:"divider.vinV",label:"Vin",type:"number"},{path:"divider.r1Ohm",label:"R1",type:"number"},{path:"divider.r2Ohm",label:"R2",type:"number"}]},{title:"RC",description:"Filtro.",fields:[{path:"rc.rOhm",label:"R",type:"number"},{path:"rc.cF",label:"C",type:"number"},{path:"rc.frequencyHz",label:"Frecuencia",type:"number"}]},{title:"PCB/Thermal",description:"Potencia.",fields:[{path:"thermal.powerW",label:"Potencia",type:"number"},{path:"thermal.thetaJaCPerW",label:"Theta",type:"number"},{path:"thermal.ambientC",label:"Ambiente",type:"number"},{path:"pcb.layers",label:"Capas",type:"number"}]}],
    endpoints:[{label:"Estado electrónica",method:"GET",path:"/_electronics_app/electronics/health",payloadMode:"current"},{label:"Pipeline electrónica",method:"POST",path:"/_electronics_app/electronics/v100000/validation/pipeline",payloadMode:"current"},{label:"Electrónica IA",method:"POST",path:"/telecom/v500000000/manual-ai/generate",payloadMode:"custom",payload:{module:"electronics",prompt:"PCB RC thermal potencia",level:"pro"}}],
    capabilities:["PCB","RC","thermal","power","IA","export"]
  },
  energy: {
    key:"energy",title:"Energy Premium Lab",badge:"Energy · PV · battery",description:"PV, batería, HVAC, coste, CO2 y perfil horario.",
    initialPayload:{pv:{areaM2:30,irradianceWm2:850,efficiency:.2},battery:{capacityKWh:12,soc:.65,loadKW:2},hvac:{areaM2:120,loadWm2:90,cop:3.2},grid:{pvKW:5,loadKW:4,batteryKW:1},cost:{eurKWh:.18,co2KgKWh:.22}},
    sections:[{title:"PV",description:"Solar.",fields:[{path:"pv.areaM2",label:"Área",type:"number"},{path:"pv.irradianceWm2",label:"Irradiancia",type:"number"},{path:"pv.efficiency",label:"Eficiencia",type:"number"}]},{title:"Batería",description:"Almacenamiento.",fields:[{path:"battery.capacityKWh",label:"Capacidad",type:"number"},{path:"battery.soc",label:"SOC",type:"number"},{path:"battery.loadKW",label:"Carga",type:"number"}]},{title:"HVAC/Coste",description:"Coste.",fields:[{path:"hvac.areaM2",label:"Área",type:"number"},{path:"hvac.loadWm2",label:"Carga",type:"number"},{path:"hvac.cop",label:"COP",type:"number"},{path:"cost.eurKWh",label:"€/kWh",type:"number"},{path:"cost.co2KgKWh",label:"CO2",type:"number"}]}],
    endpoints:[{label:"Estado energía",method:"GET",path:"/_energy_app/energy/health",payloadMode:"current"},{label:"Pipeline energía",method:"POST",path:"/_energy_app/energy/v100000/validation/pipeline",payloadMode:"current"},{label:"Energía IA",method:"POST",path:"/telecom/v500000000/manual-ai/generate",payloadMode:"custom",payload:{module:"energy",prompt:"PV bateria HVAC coste CO2",level:"pro"}}],
    capabilities:["PV","battery","HVAC","CO2","IA","export"]
  },
  iot: {
    key:"iot",title:"IoT Premium Lab",badge:"IoT · sensors · twin",description:"Sensores, gateway, personas, eventos, latencia y pérdidas.",
    initialPayload:{network:{devices:30,packets:1000,lossRate:.015,latencyMs:28},twin:{peopleMovement:{people:4,steps:120},objects:[{id:"router",x:0,y:1.2,z:0},{id:"sensor-temp",x:2,y:1.5,z:1}]},events:{motion:true,temperature:true,presence:true}},
    sections:[{title:"Red",description:"Tráfico.",fields:[{path:"network.devices",label:"Dispositivos",type:"number"},{path:"network.packets",label:"Paquetes",type:"number"},{path:"network.lossRate",label:"Pérdidas",type:"number"},{path:"network.latencyMs",label:"Latencia",type:"number"}]},{title:"Gemelo",description:"Personas.",fields:[{path:"twin.peopleMovement.people",label:"Personas",type:"number"},{path:"twin.peopleMovement.steps",label:"Pasos",type:"number"},{path:"twin.objects.0.x",label:"Router X",type:"number"},{path:"twin.objects.0.z",label:"Router Z",type:"number"}]},{title:"Eventos",description:"Sensores.",fields:[{path:"events.motion",label:"Movimiento",type:"boolean",options:bool},{path:"events.temperature",label:"Temperatura",type:"boolean",options:bool},{path:"events.presence",label:"Presencia",type:"boolean",options:bool}]}],
    endpoints:[{label:"Estado IoT",method:"GET",path:"/_iot_app/iot/health",payloadMode:"current"},{label:"Pipeline IoT",method:"POST",path:"/_iot_app/iot/v100000/validation/pipeline",payloadMode:"current"},{label:"IoT IA",method:"POST",path:"/telecom/v500000000/manual-ai/generate",payloadMode:"custom",payload:{module:"iot",prompt:"iot sensores personas eventos",level:"pro"}}],
    capabilities:["sensors","twin","events","latency","IA","export"]
  },
  transmissionLines: {
    key:"transmissionLines",title:"Transmission Lines Premium Lab",badge:"Lines · Smith · VSWR",description:"Microstrip, Smith conceptual, VSWR, reflexión, impedancia y matching.",
    initialPayload:{microstrip:{widthM:.003,heightM:.0016,epsR:4.2},reflection:{z0Ohm:50,loadOhm:75},input:{z0Ohm:50,loadOhm:75,lengthM:.05,frecuenciaGHz:2.45,epsEff:2.8},quarterWave:{z0Ohm:50,loadOhm:75,frecuenciaGHz:2.45,epsEff:2.8},stub:{enabled:true,type:"shunt",lengthLambda:.18}},
    sections:[{title:"Microstrip",description:"Geometría.",fields:[{path:"microstrip.widthM",label:"Ancho",type:"number"},{path:"microstrip.heightM",label:"Altura",type:"number"},{path:"microstrip.epsR",label:"EpsR",type:"number"}]},{title:"Reflexión",description:"Carga.",fields:[{path:"reflection.z0Ohm",label:"Z0",type:"number"},{path:"reflection.loadOhm",label:"Carga",type:"number"},{path:"input.lengthM",label:"Longitud",type:"number"},{path:"input.frecuenciaGHz",label:"Frecuencia",type:"number"}]},{title:"Matching",description:"Stub.",fields:[{path:"stub.enabled",label:"Stub",type:"boolean",options:bool},{path:"stub.type",label:"Tipo",type:"select",options:["shunt","series"]},{path:"stub.lengthLambda",label:"Longitud",type:"number"}]}],
    endpoints:[{label:"Estado líneas",method:"GET",path:"/transmission-lines/health",payloadMode:"current"},{label:"Pipeline líneas",method:"POST",path:"/transmission-lines/v200000/validation/pipeline",payloadMode:"current"},{label:"Líneas IA",method:"POST",path:"/telecom/v500000000/manual-ai/generate",payloadMode:"custom",payload:{module:"transmission_lines",prompt:"smith VSWR microstrip matching",level:"pro"}}],
    capabilities:["Smith","VSWR","microstrip","matching","IA","export"]
  },
  industrial: {
    key:"industrial",title:"Industrial Premium Lab",badge:"Industrial · QA · readiness",description:"Gauges, quality gate, incertidumbre, validación, seguridad e informes.",
    initialPayload:{quality:{backendStarts:true,frontendBuilds:true,apiHealthOk:true,examplesRun:true,hasReports:true,hasValidation:true,hasRealMeasurements:false,hasSecurityControls:false,hasBillingPlan:false},uncertainty:{components:[{name:"solver_numeric",std:1.5,unit:"dB"},{name:"material_model",std:1,unit:"dB"},{name:"measurement_noise",std:.5,unit:"dB"}]},validation:{syntheticTests:20,theoryComparisons:3,referenceSolverComparisons:1,realMeasurements:0,repeatabilityRuns:2,documentedReports:2},commercial:{workingBackend:true,workingFrontend:true,clearUseCase:true,demoScenario:true,reportGeneration:true,realValidationCase:false,billing:false,dataPersistence:false}},
    sections:[{title:"Quality",description:"Checks.",fields:[{path:"quality.backendStarts",label:"Backend",type:"boolean",options:bool},{path:"quality.frontendBuilds",label:"Frontend",type:"boolean",options:bool},{path:"quality.apiHealthOk",label:"API",type:"boolean",options:bool},{path:"quality.hasRealMeasurements",label:"Medidas",type:"boolean",options:bool},{path:"quality.hasSecurityControls",label:"Seguridad",type:"boolean",options:bool}]},{title:"Validación",description:"Madurez.",fields:[{path:"validation.syntheticTests",label:"Tests",type:"number"},{path:"validation.referenceSolverComparisons",label:"Solver",type:"number"},{path:"validation.realMeasurements",label:"Medidas",type:"number"},{path:"validation.documentedReports",label:"Informes",type:"number"}]},{title:"Comercial",description:"Readiness.",fields:[{path:"commercial.workingBackend",label:"Backend",type:"boolean",options:bool},{path:"commercial.workingFrontend",label:"Frontend",type:"boolean",options:bool},{path:"commercial.realValidationCase",label:"Caso real",type:"boolean",options:bool},{path:"commercial.billing",label:"Billing",type:"boolean",options:bool},{path:"commercial.dataPersistence",label:"Persistencia",type:"boolean",options:bool}]}],
    endpoints:[{label:"Estado industrial",method:"GET",path:"/industrial/health",payloadMode:"current"},{label:"Quality gate",method:"POST",path:"/industrial/v900000000/quality/gate",payloadMode:"current"},{label:"Uncertainty",method:"POST",path:"/industrial/v900000000/uncertainty/budget",payloadMode:"current"},{label:"Validation",method:"POST",path:"/industrial/v900000000/validation/maturity",payloadMode:"current"},{label:"Readiness",method:"POST",path:"/industrial/v900000000/commercial/readiness",payloadMode:"current"},{label:"Informe",method:"POST",path:"/industrial/v900000000/report",payloadMode:"current"}],
    capabilities:["gauges","QA","readiness","uncertainty","validation","report"]
  }
};
